const ActionCart = {
  TOGGLE_STATE_HIDDEN: 'TOGGLE_STATE_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  CLEAR_ITEM: 'CLEAR_ITEM',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
  CLEAR_CART: 'CLEAR_CART'
};

export default ActionCart;
